name: Despertar Supabase

on:
  schedule:
    # Se ejecuta todos los días a las 8:00 AM UTC
    - cron: '0 8 * * *'
  workflow_dispatch: # Esto habilita un botón para probarlo manualmente

jobs:
  wake-up:
    runs-on: ubuntu-latest
    steps:
      - name: Llamar a la API Serverless
        # He puesto la URL que aparece en tu captura de pantalla
        run: curl -I https://sistema-de-finanzas.vercel.app/api/keep-alive
